# Generated by Django 4.1.4 on 2023-03-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_delete_user_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
