# Generated by Django 4.1.4 on 2023-03-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
