# Generated by Django 4.1.4 on 2023-03-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='phone_numb',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='user_name',
        ),
    ]
