# Generated by Django 4.1.4 on 2023-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_student_options_student_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clasa',
            field=models.CharField(choices=[('DAHOM', 'دهم'), ('YAZDAHOM', 'یازدهم'), ('DAVAZDAHOM', 'دوازدهم'), ('FAREGHOLTAHSIH', 'فارغ التحصیل')], default='NOT_SET', max_length=16),
        ),
    ]
